# Generated by Django 5.1.2 on 2024-10-31 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
